/* @flow */

export const GET_IMAGES_REQUEST = "INITIAL_SCREEN_GET_IMAGES_REQUEST";
export const GET_IMAGES_RESPONSE = "INITIAL_SCREEN_GET_IMAGES_RESPONSE";
export const GET_IMAGES_ERROR = "INITIAL_SCREEN_GET_IMAGES_ERROR";