# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoolStuff' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoolStuff

  pod 'NYSegmentedControl', :git => 'https://github.com/shapehq/NYSegmentedControl.git'
  pod 'SHPKeyboardAwareness', :git => 'https://github.com/shapehq/SHPKeyboardAwareness.git'
  pod 'NYTPhotoViewer', :git => 'https://github.com/NYTimes/NYTPhotoViewer.git'


  target 'CoolStuffTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CoolStuff-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoolStuff-tvOS

  target 'CoolStuff-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
